import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'


export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Example Next App with secrets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Automated Deployment with secrets!&nbsp;
            <code className={styles.code}>
              Here is some server side data {data.html_url}
            </code>
          </p>
          <div>
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
          </div>
        </div>

        <div className={styles.center}>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 >
              Docs <span>-&gt;</span>
            </h2>
            <p >
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 >
              Learn <span>-&gt;</span>
            </h2>
            <p >
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 >
              Templates <span>-&gt;</span>
            </h2>
            <p >
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 >
              Deploy <span>-&gt;</span>
            </h2>
            <p >
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://api.github.com/repos/vercel/next.js')
  const json = await res.json()

  console.log('server side db password ', process.env.NEO4J_PASSWORD);
  console.log('server side db url ', process.env.NEO4J_UR);
  console.log('server side username ', process.env.NEO4J_USERNAME);

  console.log(json.html_url);

  return { props: { data: json } }
}
