name: Push source to openshift and trigger a build and deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Provision environment variables and deploy to OpenShift with nodeshift
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Create .env.local with secret environment variables
        run: |
          echo "NEXT_PUBLIC_SEKRET=${{ secrets.NEXT_PUBLIC_SEKRET }}" >> .env.local
          echo "SEKRET_TOKEN=${{ secrets.SEKRET_TOKEN }}" >> .env.local
      - name: Nodeshift deploy
        run: |
          npx nodeshift NPM_RUN="npm start" --deploy.port 3000 --expose \
            --username=${{ secrets.OC_USERNAME }} --password="${{ secrets.OC_PASSWORD }}" \
            --server=${{ secrets.OC_SERVER }} \
            --namespace.name ${{ secrets.OC_NAMESPACE }}

